# Generated by Django 5.1.2 on 2024-10-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('comentario', models.TextField()),
            ],
        ),
    ]
