# Generated by Django 5.1.2 on 2024-10-28 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
