# Generated by Django 5.1.2 on 2024-10-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='email',
            new_name='nome',
        ),
    ]
