# Generated by Django 5.1.2 on 2024-10-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_email_comentario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='nome',
            field=models.TextField(),
        ),
    ]
