# Generated by Django 5.1.2 on 2024-10-28 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_comentario_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nome',
            new_name='nom',
        ),
    ]
