# Generated by Django 5.1.2 on 2024-10-28 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_nome_comentario_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nom',
            new_name='nome',
        ),
    ]
